/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentMode = IDL.Record({
  'chequeNumber' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'mode' : IDL.Text,
  'bankName' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'transactionId' : IDL.Opt(IDL.Text),
});
export const Payment = IDL.Record({
  'user' : IDL.Principal,
  'invoiceNumbers' : IDL.Vec(IDL.Nat),
  'paymentModes' : IDL.Vec(PaymentMode),
});

export const idlService = IDL.Service({
  'clearAllPayments' : IDL.Func([], [], []),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getPaymentsByInvoiceNumber' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getPaymentsByMode' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
  'getPaymentsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'submitPayment' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Vec(PaymentMode)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentMode = IDL.Record({
    'chequeNumber' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'mode' : IDL.Text,
    'bankName' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'transactionId' : IDL.Opt(IDL.Text),
  });
  const Payment = IDL.Record({
    'user' : IDL.Principal,
    'invoiceNumbers' : IDL.Vec(IDL.Nat),
    'paymentModes' : IDL.Vec(PaymentMode),
  });
  
  return IDL.Service({
    'clearAllPayments' : IDL.Func([], [], []),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getPaymentsByInvoiceNumber' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getPaymentsByMode' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
    'getPaymentsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'submitPayment' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Vec(PaymentMode)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };