/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Payment = IDL.Record({
  'chequeDate' : IDL.Opt(IDL.Text),
  'chequeNumber' : IDL.Opt(IDL.Text),
  'user' : IDL.Principal,
  'chequeAmount' : IDL.Opt(IDL.Nat),
  'bankName' : IDL.Opt(IDL.Text),
  'invoiceNumber' : IDL.Nat,
  'neftAmount' : IDL.Opt(IDL.Nat),
  'paymentMode' : IDL.Text,
  'neftDate' : IDL.Opt(IDL.Text),
  'transactionId' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getPaymentsByInvoiceNumber' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getPaymentsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'submitPayment' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Payment = IDL.Record({
    'chequeDate' : IDL.Opt(IDL.Text),
    'chequeNumber' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
    'chequeAmount' : IDL.Opt(IDL.Nat),
    'bankName' : IDL.Opt(IDL.Text),
    'invoiceNumber' : IDL.Nat,
    'neftAmount' : IDL.Opt(IDL.Nat),
    'paymentMode' : IDL.Text,
    'neftDate' : IDL.Opt(IDL.Text),
    'transactionId' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getPaymentsByInvoiceNumber' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getPaymentsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'submitPayment' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };